[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 9600
lib_ldf_mode = deep+
lib_deps =
  bogde/HX711@0.7.5
  marcoschwartz/LiquidCrystal_I2C@1.1.4
  gyverlibs/EncButton@3.7.6
